/********************************************************************
* guiDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error guiDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevguiDict();
extern G__DLLEXPORT void G__set_cpp_environmentguiDict();
extern G__DLLEXPORT void G__cpp_setup_tagtableguiDict();
extern G__DLLEXPORT void G__cpp_setup_inheritanceguiDict();
extern G__DLLEXPORT void G__cpp_setup_typetableguiDict();
extern G__DLLEXPORT void G__cpp_setup_memvarguiDict();
extern G__DLLEXPORT void G__cpp_setup_globalguiDict();
extern G__DLLEXPORT void G__cpp_setup_memfuncguiDict();
extern G__DLLEXPORT void G__cpp_setup_funcguiDict();
extern G__DLLEXPORT void G__cpp_setupguiDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "C:/ArggsComputerEcke/Simple_Root_GUI/compiled_gui/gui.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__guiDictLN_string;
extern G__linked_taginfo G__guiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__guiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__guiDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__guiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__guiDictLN_TList;
extern G__linked_taginfo G__guiDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__guiDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__guiDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__guiDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__guiDictLN_TQObjSender;
extern G__linked_taginfo G__guiDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__guiDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__guiDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__guiDictLN_iteratorlErandom_access_iterator_tagcOpairlEunsignedsPintcOintgRcOlongcOpairlEunsignedsPintcOintgRmUcOpairlEunsignedsPintcOintgRaNgR;
extern G__linked_taginfo G__guiDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__guiDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__guiDictLN_TGTextButton;
extern G__linked_taginfo G__guiDictLN_TGVerticalFrame;
extern G__linked_taginfo G__guiDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__guiDictLN_TGMainFrame;
extern G__linked_taginfo G__guiDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__guiDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__guiDictLN_iteratorlErandom_access_iterator_tagcOTStreamerInfomUcOlongcOTStreamerInfomUmUcOTStreamerInfomUaNgR;
extern G__linked_taginfo G__guiDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__guiDictLN_listlETGListTreeItemmUcOallocatorlETGListTreeItemmUgRsPgR;
extern G__linked_taginfo G__guiDictLN_maplETGListTreeItemmUcOconstsPcharmUcOlesslETGListTreeItemmUgRcOallocatorlEpairlETGListTreeItemmUsPconstcOconstsPcharmUgRsPgRsPgR;
extern G__linked_taginfo G__guiDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__guiDictLN_ui;

/* STUB derived class for protected member access */
